name: Sync Fork

on:
  schedule:
    - cron: '0 17 * * MON' # 5pm UTC every Monday
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.9
        with:
          owner: ensomata
          base: source
          head: source
